# Generated by Django 4.2.2 on 2023-06-28 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Thrift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thrift.shoppingcart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thrift.product')),
            ],
        ),
    ]
