# Generated by Django 4.2.2 on 2023-06-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thrift', '0002_shoppingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
