# Generated by Django 4.2.2 on 2023-06-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thrift', '0003_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_accepted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
