# Generated by Django 4.2.2 on 2023-06-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Thrift', '0005_remove_order_products_remove_order_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('postal', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('finished', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thrift.shoppingcart')),
            ],
        ),
    ]
